-- AI Insights (meta-review): persists Claude-generated syntheses over a user's
-- recent trade-review scorecards. Generated by /api/trade-review/insights
-- (auth + 2/day quota, see 0003); listed/deleted client-side under RLS.
--
-- No migration runner is wired up for this project, so apply by hand:
-- Supabase dashboard → SQL Editor → paste → Run. Idempotent (safe to re-run).
--
-- Access model: same anon + RLS model as trade_reviews (0001). The insert-own
-- policy means a user could technically insert a fabricated insight into their
-- OWN journal via the anon client — accepted limitation (this repo has no
-- service-role key by design; fabrication only pollutes the author's own data,
-- exactly like trade_reviews).

begin;

create extension if not exists "pgcrypto";

create table if not exists public.trade_review_insights (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at  timestamptz not null default now(),
  period_kind text not null check (period_kind in ('last_n', 'last_7d')),
  period_n    int check (period_n in (3, 5, 10)),
  review_ids  uuid[] not null check (array_length(review_ids, 1) >= 3),
  insight     jsonb not null,  -- full TradeInsight payload
  model       text not null
);

create index if not exists trade_review_insights_user_created_idx
  on public.trade_review_insights (user_id, created_at desc);

alter table public.trade_review_insights enable row level security;

-- Each user sees and mutates only their own rows.
drop policy if exists "trade_review_insights_select_own" on public.trade_review_insights;
create policy "trade_review_insights_select_own"
  on public.trade_review_insights for select
  using (auth.uid() = user_id);

drop policy if exists "trade_review_insights_insert_own" on public.trade_review_insights;
create policy "trade_review_insights_insert_own"
  on public.trade_review_insights for insert
  with check (auth.uid() = user_id);

drop policy if exists "trade_review_insights_delete_own" on public.trade_review_insights;
create policy "trade_review_insights_delete_own"
  on public.trade_review_insights for delete
  using (auth.uid() = user_id);

-- Explicit Data API grants (don't rely on project defaults): no anon access,
-- no updates — insights are immutable once written.
revoke all on table public.trade_review_insights from anon;
grant select, insert, delete on table public.trade_review_insights to authenticated;
revoke update on table public.trade_review_insights from authenticated;

commit;
